/**
 * Verifier Agent
 * Performs strict validation and sanity checking on structured agent outputs
 * before any Firestore write operations or client returns.
 *
 * Enforces:
 * - JSON and schema integrity
 * - Daily task time limits and measurable deliverables
 * - Duplicate task prevention
 * - Prerequisite constraints
 * - Quiz structure and correctness bounds
 */
class VerifierAgent {
  /**
   * Validate daily tasks generated for a user.
   */
  static validateDailyTasks({ tasks = [], dailyHoursBudget = 4, existingTasks = [] }) {
    const errors = [];
    const maxMinutes = Math.max(dailyHoursBudget * 60, 60);

    if (!Array.isArray(tasks) || tasks.length === 0) {
      return { valid: false, errors: ['Tasks must be a non-empty array (2-4 tasks expected).'] };
    }

    if (tasks.length < 1 || tasks.length > 5) {
      errors.push(`Expected 2-4 daily tasks, received ${tasks.length}`);
    }

    let totalMinutes = 0;
    const existingTitlesNormalized = new Set(
      existingTasks.map(t => (t.title || '').toLowerCase().trim())
    );

    const validatedTasks = [];

    for (let i = 0; i < tasks.length; i++) {
      const task = tasks[i];
      if (!task.title || typeof task.title !== 'string' || task.title.trim().length < 5) {
        errors.push(`Task #${i + 1} has missing or too short title.`);
        continue;
      }

      const normalizedTitle = task.title.toLowerCase().trim();
      // Duplicate detection against existing tasks
      if (existingTitlesNormalized.has(normalizedTitle)) {
        errors.push(`Duplicate task detected: "${task.title}" already exists for this scheduled date.`);
        continue;
      }
      existingTitlesNormalized.add(normalizedTitle);

      const estimate = parseInt(task.estimate_minutes, 10) || 45;
      if (estimate < 15 || estimate > 180) {
        errors.push(`Task #${i + 1} estimate (${estimate}m) is out of bounds (15m - 180m).`);
      }
      totalMinutes += estimate;

      validatedTasks.push({
        ...task,
        title: task.title.trim(),
        description: (task.description || '').trim(),
        estimate_minutes: estimate,
        status: task.status === 'done' ? 'done' : 'todo',
        source: task.source || 'llm_generated'
      });
    }

    if (totalMinutes > maxMinutes * 1.2) {
      errors.push(`Total daily task time (${totalMinutes}m) exceeds user daily limit (${maxMinutes}m).`);
    }

    return {
      valid: errors.length === 0 && validatedTasks.length > 0,
      errors,
      totalMinutes,
      validatedTasks
    };
  }

  /**
   * Validate quiz questions generated by the Tutor Agent.
   */
  static validateQuizQuestions(questions) {
    if (!Array.isArray(questions) || questions.length === 0) {
      return { valid: false, errors: ['Quiz questions must be a non-empty array.'], validatedQuestions: [] };
    }

    const errors = [];
    const validatedQuestions = [];

    questions.forEach((q, idx) => {
      if (!q.question || typeof q.question !== 'string') {
        errors.push(`Question #${idx + 1} is missing question prompt.`);
        return;
      }
      if (!Array.isArray(q.options) || q.options.length < 2) {
        errors.push(`Question #${idx + 1} must have at least 2 options.`);
        return;
      }
      const correctIndex = parseInt(q.correctIndex, 10);
      if (isNaN(correctIndex) || correctIndex < 0 || correctIndex >= q.options.length) {
        errors.push(`Question #${idx + 1} has invalid correctIndex (${q.correctIndex}).`);
        return;
      }

      validatedQuestions.push({
        id: q.id || `q_${idx + 1}`,
        question: q.question.trim(),
        options: q.options.map(opt => String(opt).trim()),
        correctIndex,
        explanation: (q.explanation || 'Verified concept answer.').trim()
      });
    });

    return {
      valid: errors.length === 0 && validatedQuestions.length > 0,
      errors,
      validatedQuestions
    };
  }

  /**
   * Validate job matches before writing to job_matches collection.
   */
  static validateJobMatches(matches = []) {
    if (!Array.isArray(matches)) {
      return { valid: false, errors: ['Job matches must be an array.'], validatedMatches: [] };
    }

    const seenIds = new Set();
    const validatedMatches = [];

    matches.forEach(m => {
      const jobId = m.post?.id || m.job_id;
      if (!jobId || seenIds.has(jobId)) return;
      seenIds.add(jobId);

      const score = Math.max(0, Math.min(100, Math.round(Number(m.match?.match_score || m.match_score) || 75)));
      validatedMatches.push({
        ...m,
        match: {
          ...(m.match || {}),
          match_score: score
        }
      });
    });

    return {
      valid: true,
      errors: [],
      validatedMatches
    };
  }
}

module.exports = VerifierAgent;
